## Python Libraries for Datascience
- Numpy 
- pandas
- seaborn
- matplotlib

## Numpy
- numerical python
- Arrays
    - single dimension arrays
    - Two dimension arrys
    - Multi dimensional arrays
- linear algebra,fourier transforms,materics
- 2005 Travis  oliphant

In [2]:
pip  install numpy

Note: you may need to restart the kernel to use updated packages.


In [3]:
import numpy

In [5]:
#dir(numpy)

In [6]:
from numpy import *#the modules can be from numpy

In [7]:
help(numpy.array)

Help on built-in function array in module numpy:

array(...)
    array(object, dtype=None, copy=True, order='K', subok=False, ndmin=0)
    
    Create an array.
    
    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        __array__ method returns an array, or any (nested) sequence.
    dtype : data-type, optional
        The desired data-type for the array.  If not given, then the type will
        be determined as the minimum type required to hold the objects in the
        sequence.
    copy : bool, optional
        If true (default), then the object is copied.  Otherwise, a copy will
        only be made if __array__ returns a copy, if obj is a nested sequence,
        or if a copy is needed to satisfy any of the other requirements
        (`dtype`, `order`, etc.).
    order : {'K', 'A', 'C', 'F'}, optional
        Specify the memory layout of the array. If object is not an array, the
        newly crea

In [8]:
import numpy as np
print(np.__version__)

1.18.1


## 1D-Array

In [20]:
## craete array
import numpy as np
a=np.array([1,23,4])
print(a)
print(type(a))

[ 1 23  4]
<class 'numpy.ndarray'>


In [25]:
print(ndim(a))## type  of dimension

1


In [26]:
print(shape(a))## no of columns and rows

(3,)


In [30]:
print(size(a)) # no of elements

3


In [31]:
#help(numpy.shape)

In [34]:
arr=np.array(4)##
print(arr)
print(type(arr))
print(ndim(arr))

4
<class 'numpy.ndarray'>
0


## 2D-arrays

In [46]:
import numpy as np
a=np.array([[1,2,3],[4,6,3]])
print(a)
print(type(a))
print(ndim(a))
print(shape(b))

[[1 2 3]
 [4 6 3]]
<class 'numpy.ndarray'>
2
(1, 3, 2)


## 3D-array

In [41]:

ar1=np.array([[[5,4],[2,3],[7,6]]])
print(ar1)
ndim(ar1)

[[[5 4]
  [2 3]
  [7 6]]]


3

In [42]:
## craeting array with tuple 
arr=np.array((1,2,4,7))
print(arr)
ndim(arr)


[1 2 4 7]


1

In [45]:
b=np.array([[[1,3],[5,6],[11,2]]])
print(b)
print(ndim(b))
print(type(b))
print(size(b))
print(shape(b))

[[[ 1  3]
  [ 5  6]
  [11  2]]]
3
<class 'numpy.ndarray'>
6
(1, 3, 2)


In [49]:
x=np.array([1,2,34],ndmin=3)
print(x)

[[[ 1  2 34]]]


In [53]:
import numpy as np
a=np.array([1,2,3])
print(a)
print(type(a))
print(ndim(a))
b=np.array([[1,2],[3,4]])
print(b)
print(type(b))
print(ndim(b))
c=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(b)
print(type(c))
print(ndim(c))

[1 2 3]
<class 'numpy.ndarray'>
1
[[1 2]
 [3 4]]
<class 'numpy.ndarray'>
2
[[1 2]
 [3 4]]
<class 'numpy.ndarray'>
3


## Accessing elements in 1D- Array

In [54]:
import numpy as np
x=np.array([1,6,4,9])
print(x)

[1 6 4 9]


In [55]:
x[0]

1

In [56]:
x[-1]

9

In [57]:
x[3]

9

In [58]:
print(x[2]+x[3])

13


## accesing of elements in 2D-array

In [59]:
import numpy as np
x1=np.array([[1,6,5],[3,4,5]])
print(x1)

[[1 6 5]
 [3 4 5]]


In [60]:
x1.shape# rows and columns

(2, 3)

In [64]:
x1[0][0]

1

In [65]:
x1[0,1]

6

In [66]:
x1[1][1]

4

In [67]:
x1[1,2]

5

## Accesing elements in 3D-Array

In [68]:
import numpy as np
x2=np.array([[[1,6,4],[3,55,7],[77,5,3]]])
print(x2)

[[[ 1  6  4]
  [ 3 55  7]
  [77  5  3]]]


In [72]:
x2[0,0,0]

1

In [74]:
x2[0,0,1]## row,column,element


6

In [77]:
x2[0,1,1] 


55

In [78]:
x1=np.array([[[1,2,3],[4,5,6],[7,8,9],[10,11,2]]])

In [79]:
x1

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11,  2]]])

In [83]:
x1[0,2,2]

9

In [84]:
##0-[1,2,3][4,5,6]--1=[4,5,6]=2==6
##[7,8,9][10,11,2]


## Slicling[start:end:step]

In [89]:
x

array([1, 6, 4, 9])

In [91]:
x[0:3]

array([1, 6, 4])

In [92]:
x[2:]

array([4, 9])

In [94]:
x[-3:-1]

array([6, 4])

In [149]:
x1=np.array([1,2,5,4,8,9,7,5])
x1

array([1, 2, 5, 4, 8, 9, 7, 5])

In [100]:
x1[1:5]

array([2, 5, 4, 8])

In [101]:
x1[1:5:2]

array([2, 4])

In [103]:
x1[2:4]

array([5, 4])

## Slicling in 2D-Array

In [105]:
x2=np.array([[1,2,4,6],[2,3,7,9],[3,5,88,77]])
x2

array([[ 1,  2,  4,  6],
       [ 2,  3,  7,  9],
       [ 3,  5, 88, 77]])

In [109]:
x2[0:]

array([[ 1,  2,  4,  6],
       [ 2,  3,  7,  9],
       [ 3,  5, 88, 77]])

In [124]:
x2[0,0:3]##,==refers to columns

array([1, 2, 4])

In [120]:
x2[1,1:4]


array([3, 7, 9])

In [129]:
x2[0:3,0:1]## 0 th index columns sccessing


array([[1],
       [2],
       [3]])

In [131]:
x2[0:3,1:2]# 1index column accessing

array([[2],
       [3],
       [5]])

In [138]:
x2[:3,0:4:3]

array([[ 1,  6],
       [ 2,  9],
       [ 3, 77]])

In [140]:
x2[:3,0:6:2]

array([[ 1,  4],
       [ 2,  7],
       [ 3, 88]])

In [143]:
for i in x2:
    #print(i)
    for j in i:
        print(j)

1
2
4
6
2
3
7
9
3
5
88
77


## Reshape of array

In [150]:
x1

array([1, 2, 5, 4, 8, 9, 7, 5])

In [151]:
x1.shape

(8,)

In [152]:
x1.size

8

In [156]:
x2=x1.reshape(2,4)
x2

array([[1, 2, 5, 4],
       [8, 9, 7, 5]])

In [157]:
x2=x1.reshape(4,2)
x2

array([[1, 2],
       [5, 4],
       [8, 9],
       [7, 5]])

In [159]:
x2=x1.reshape(8,1)
x2

array([[1],
       [2],
       [5],
       [4],
       [8],
       [9],
       [7],
       [5]])

In [160]:
x2=x1.reshape(5,4)#5*4=20
x2

ValueError: cannot reshape array of size 8 into shape (5,4)

In [170]:
a1=np.array([[1,2,3],[3,4,5]])
a1

array([[1, 2, 3],
       [3, 4, 5]])

In [172]:
print(a1.size)
a1.ndim

6


2

In [174]:
a3=a1.reshape(1,2,3)
print(a3.ndim)
print(a3)

3
[[[1 2 3]
  [3 4 5]]]
